name: Deploy to Coolify
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify Deploy
        run: |
          curl -X GET "https://coolify.vyvox.fr/api/v1/deploy?uuid=znpe9znk04r6m35n0nokcua6&force=false" \
          -H "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}"